Add 3.2.5
csconfederation/rulebook pull request #5
Opened 2022-10-25 23:45 UTC by 42Firehawk

Proposed:
> 3.2.5    A GM that contacts a contracted player from a different franchise with the intention of getting that player to join their franchise and without the player's GM's permission will be subject to punishment at admin discretion. Direct evidence of this contact/intention is required.

2022-10-26 12:44 UTC, techlover1 approved these changes

2022-10-30 05:16 UTC, cokenyo requested changes
Remove the extra space on the new line 30 between '\&emsp;' and the beginning of the rule.

2022-10-30 06:27 UTC, 42Firehawk commented
Updated to remove the extra space on line 30

2022-10-31 13:02 UTC, loganramhap approved these changes
╰(*°▽°*)╯

2022-11-04 04:05 UTC, cokenyo approved these changes

2022-11-04 04:05 UTC, merged